### ISSUE TITLE
Feature Request: Enable directly publishing NuGet packages

### ISSUE THREAD

**Issue by randymarsh77** [Faithlife/FaithlifeBuild#47]
**Problem**
The current `publish` target assumes some build intermediates (`obj` directory) when determining information about what to publish. This is a problem for parallelized or distributed workflows that aggregate NuGet artifacts in a final publishing step, where there aren't any other build intermediates.

**Idea**
Add a new target, `publish-nuget-output`, which runs all the same publish logic without requiring build intermediates. This is a dedicated target as to avoid ambiguous behavior and requirements if trying to accomplish this using the existing `publish` step, but will still ensure proper tagging and documentation updates are made.

**Comment by ejball** [comment]
>assumes some build intermediates (obj directory) 

I'm not sure what you mean by this. It isn't true as far as I know. IIRC it builds packages to a temporary directory so that it knows what packages were created (vs. what packages were already in the output directory).

**Comment by randymarsh77** [comment]
Implemented in [5.17.0](https://github.com/Faithlife/FaithlifeBuild/pull/52)
